### ISSUE TITLE
Could you please provide a link of 'vgg_normalised.pth'?

### ISSUE THREAD

**Issue by chenkai-666** [Huage001/AdaAttN#1]
Thank you

**Comment by Huage001** [comment]
Hi, thank you for your interest!
This file is already included in the [Google Drive link](https://drive.google.com/file/d/1XvpD1eI4JeCBIaW5uwMT6ojF_qlzM_lo/view?usp=sharing). 
If you only want 'vgg_normalised.pth' file, you can also download it from [here](https://drive.google.com/file/d/1BinnwM5AmIcVubr16tPTqxMjUCE8iu5M/view?usp=sharing).

**Comment by chenkai-666** [comment]
Thanks！
