### ISSUE TITLE
About the loss

### ISSUE THREAD

**Issue by KevinMarkVine** [Huage001/AdaAttN#10]
Hi,  I am interested in this article AdaAttN. The paper only introduced two losses, Lgs and Llf, but why is there a content loss in your code?

**Comment by Huage001** [comment]
Hello! Thanks for your interest!
Content loss is only used for the ablation study. In our default setting, we only use L_lf and L_gs.

**Comment by KevinMarkVine** [comment]
邮件已收到，但没有Check，这是自动回复信息
