### ISSUE TITLE
About the inference_frame.py in video infererce

### ISSUE THREAD

**Issue by diaodeyi** [Huage001/AdaAttN#11]
Hi , thanks for your code. As for the code in inference_frame.py,  the line 110 in class AttnAdaINCos
`      G_norm = torch.sqrt((G ** 2).sum(1).view(b, 1, -1))
        b, _, h, w = F.size()
        F = F.view(b, -1, w * h)
        F_norm = torch.sqrt((F ** 2).sum(1).view(b, -1, 1))
        F = F.permute(0, 2, 1)
        S = torch.relu(torch.bmm(F, G) / (F_norm + 1e-5) / (G_norm + 1e-5) + 1)
        # S: b, n_c, n_s
        S = S / (S.sum(dim=-1, keepdim=True) + 1e-5)`
1. i think the F_norm and the G_norm should be calculated by sum(2) not sum(1)
2. why you add the 1e-5 in three places in code?

**Comment by diaodeyi** [comment]
G_norm = torch.sqrt((G ** 2).sum(1).view(b, 1, -1))
        b, _, h, w = F.size()
        F = F.view(b, -1, w * h)
        F_norm = torch.sqrt((F ** 2).sum(1).view(b, -1, 1))
        F = F.permute(0, 2, 1)
        S = torch.relu(torch.bmm(F, G) / (F_norm + 1e-5) / (G_norm + 1e-5) + 1)
        # S: b, n_c, n_s
        S = S / (S.sum(dim=-1, keepdim=True) + 1e-5)

**Comment by diaodeyi** [comment]
sorry. I got it. I want ask one more question about paper. The self-attention use cos-similarity in paper is use '1+...' not  '1-..' as usual. Can you figure it out ? the code is as below:
`S = torch.relu(torch.bmm(F, G) / (F_norm + 1e-5) / (G_norm + 1e-5) + 1)`
the '+ 1' in end

**Comment by Huage001** [comment]
Hello,

First, it should be an increasing function with respect to the normalized correlation, so the sign of the normalized correlation should be positive. Second, it should always be greater than 0 and the range of normalized correlation is [-1,1], so we plus 1.

By the way, the name of (1-…) as you write is 'cosine distance' instead of 'cosine similarity'.

**Comment by diaodeyi** [comment]
Ooh, It's my fault. Thank you so much!  There is a result table in paper. If it's convenient for you to provide the style images?
<img width="1326" alt="截屏2022-02-22 下午9 05 47" src="https://user-images.githubusercontent.com/48873381/155138384-ef00c68d-8ca7-45ea-b513-027d02d02df7.png">
:

**Comment by Huage001** [comment]
They are from the official repo of AdaIN (https://github.com/xunhuang1995/AdaIN-style/tree/master/input/style), in the alphabet order.
