### ISSUE TITLE
About the adaattn_model.py

### ISSUE THREAD

**Issue by weiyang001** [Huage001/AdaAttN#12]
Hi , thanks for your code. I have two questions about it.

1. I don't understand what `self.device` means here, it doesn't seem to be defined.
![1647223113(1)](https://user-images.githubusercontent.com/89854237/158091916-4ba31383-9e31-4053-bed0-86b8927fa39b.jpg)

2. In addition, I would like to ask whether _local feature loss_ is taking up too much memory.Because I ran out of memory when I tried to import this module into other code.

Thanks!

**Comment by fengxiaoming520** [comment]
> 

self.device is defined in class BaseModel.

**Comment by weiyang001** [comment]
Thanks for your answer!
