### ISSUE TITLE
what should i set the numbers of lambda_content??

### ISSUE THREAD

**Issue by zhongyuning** [Huage001/AdaAttN#4]
In my screen, the lambda_content is always zero, i find the lambda_content is zero by default, i dont know how to set it , could you  tell me how to set? Thanks!

**Comment by Huage001** [comment]
Just change '--lambda_content 0' to '--lambda_content xx' in train_adaattn.sh.
For the exact value, I think xx=1~10 will produce reasonable results.

**Comment by zhongyuning** [comment]
Thanks!! I will try it
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Huage001/AdaAttN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Huage001/AdaAttN] what should i set the numbers of lambda_content?? (Issue #4)





 
Just change '--lambda_content 0' to '--lambda_content xx' in train_adaattn.sh.
 For the exact value, I think xx=1~10 will produce reasonable results.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
