### ISSUE TITLE
About the pretrained VGG

### ISSUE THREAD

**Issue by diaodeyi** [Huage001/AdaAttN#6]
Hi , i want to konw the pre-trained VGG encoder is pre-trained on which dataset?

**Comment by Huage001** [comment]
Hi,
The pre-trained VGG encoder is pre-trained on ImageNet1k. You can download it from [here](https://drive.google.com/file/d/1BinnwM5AmIcVubr16tPTqxMjUCE8iu5M/view?usp=sharing).
