### ISSUE TITLE
Mean-variance-norm and Instance Norm

### ISSUE THREAD

**Issue by sonnguyen129** [Huage001/AdaAttN#8]
Hi @Huage001 
I read the paper and found that mean variance norm mean 'mean-variance channel-wise norm' works quite like instance norm. Can you explain to me why use ```mean-variance-norm``` function instead of ```instance norm```?
Thank you so much.

**Comment by Huage001** [comment]
Hello,
Actually, the difference between them is little. One difference is that mean-variance-norm uses unbiased variance estimation while instance norm uses the biased one. You can also try with instance norm but I think there may not be substantial effect on final outputs.

**Comment by sonnguyen129** [comment]
I have 1 more question. When testing, is the output size 256 x 256, can the models produce other sizes?

**Comment by Huage001** [comment]
In our experiments, the default output size is 512x512. Other sizes are also OK. But it would be better to set the size as a multiple of 16, to avoid problems on down sample and up sample operations.

**Comment by sonnguyen129** [comment]
Hi @Huage001 
Thank you for your reply. When I read [MUNIT paper](https://arxiv.org/pdf/1804.04732.pdf), those authors said that IN will remove importance style information. 
![image](https://user-images.githubusercontent.com/55862188/148643020-928f97cd-8c22-4500-84d4-b18c024cdcc2.png)

But in [AdaAttN paper](https://arxiv.org/pdf/2108.03647.pdf). Authors use Norm in AdaAttN module.
![image](https://user-images.githubusercontent.com/55862188/148643174-d72d79d4-be7f-4d58-964b-c59f80f88fcb.png)

This makes me quite confused. Please explain to me.

**Comment by Huage001** [comment]
Since IN removes the style information, we can compute content-wise similarity between content and style images after IN. This similarity is used to aggregate style feature F_s, as shown in the third row of the above figure. The aggregated style feature is not proceeded with IN.

**Comment by sonnguyen129** [comment]
Hi @Huage001 
Thank you for your reply. What does ```adaptive``` in ```adative attention normalization``` mean? Can models that can represent formulas like AdaAttN be called ```adaptive```? Is [SANet](https://arxiv.org/pdf/1812.02342.pdf) adaptive, I didn't see the author mention it all

**Comment by Huage001** [comment]
The name of AdaAttN actually follows AdaIN. "Adaptive" is used to describe the normalization operation, whose parameters are dynamically (adaptively) dependent on the style feature. From this perspective, we can also call SANet, even all the current attention methods "adaptive".

**Comment by sonnguyen129** [comment]
Hi @Huage001 
Do you think swapping the content and style features for the SANet module or the AdaAttN module makes any difference?
![image](https://user-images.githubusercontent.com/55862188/148682756-e93ca199-0e13-4987-8736-a262b1f5b3c5.png)
And
![image](https://user-images.githubusercontent.com/55862188/148682809-11a33522-ad50-46cc-a46b-014ba44e2130.png)
Thank you so much

**Comment by Huage001** [comment]
In that case, you can imagine the content image would serve as "style reference" while the style image would serve as "content reference". Typically in attention-based style transfer, query (Q) should be contents, key (K) and value (V) should be styles.

**Comment by sonnguyen129** [comment]
Hi @Huage001 
Thank you for your explaination. I will close this issue. I will re-open if I have another question in the future
Wish you all health, success and happiness!
Best regards,
Son Nguyen.
